# terminal integration
if [[ ! -v SSH_CONNECTION ]]; then
  WEZTERM_SH_FILE="${HOME}/.config/zsh/wezterm.sh"
  if [[ -e "${WEZTERM_SH_FILE}" ]]; then
    source "${WEZTERM_SH_FILE}"
  fi
fi

# asdf completions
if [[ -v ASDF_DATA_DIR ]]; then
  _asdf_completions="${ASDF_DATA_DIR}/completions/_asdf"
  if [[ ! -e "$_asdf_completions" ]]; then
    mkdir -p "$(dirname "$_asdf_completions")"
    asdf completion zsh >"$_asdf_completions"
  fi
  fpath=("$(dirname "$_asdf_completions")" $fpath)
fi

# zim
ZIM_CONFIG_FILE="${HOME}/.config/zsh/zimrc"
ZIM_HOME="${HOME}/.cache/zim"

if [[ ! -e "${ZIM_HOME}/zimfw.zsh" ]]; then
  curl -fsSL --create-dirs -o "${ZIM_HOME}/zimfw.zsh" \
    https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

if [[ ! "${ZIM_HOME}/init.zsh" -nt "${ZIM_CONFIG_FILE}" ]]; then
  source "${ZIM_HOME}/zimfw.zsh" init
fi

if [[ -d "${ZIM_HOME}" ]]; then
  source "${ZIM_HOME}/init.zsh"
fi

# starship
export STARSHIP_CONFIG="${HOME}/.config/starship/starship.toml"
if ! which starship >/dev/null; then
  curl -sS https://starship.rs/install.sh | sh -s -- -b "${HOME}/.local/bin" -y
fi
if which starship >/dev/null; then
  eval "$(starship init zsh)"
fi

# atuin (history)
if which atuin >/dev/null; then
  eval "$(atuin init zsh)"
fi

# zoxide
if which zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

# eza
if which eza >/dev/null; then
  alias ls="eza -b"
fi
EZA_ROOT="${HOME}/.eza"
if [[ -d "${EZA_ROOT}" ]]; then
  fpath=("${EZA_ROOT}/completions/zsh" $fpath)
fi

# just
if which just >/dev/null; then
  eval "$(just --completions zsh)"
fi

# select word style
autoload -U select-word-style
select-word-style bash

# customization
alias without_proxy='env http_proxy="" https_proxy=""'
